// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIC6EfvwdRxTxBcCou3g3do7_Tlxq6N4',
    appId: '1:542970368595:web:87d88e1d7a2fbab0ae2ca6',
    messagingSenderId: '542970368595',
    projectId: 'myberikan2-d4a1c',
    authDomain: 'myberikan2-d4a1c.firebaseapp.com',
    storageBucket: 'myberikan2-d4a1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcbLaTAB4H6aal6_SlTXXjAelEPn8C4A',
    appId: '1:542970368595:android:dde968308461f6b9ae2ca6',
    messagingSenderId: '542970368595',
    projectId: 'myberikan2-d4a1c',
    storageBucket: 'myberikan2-d4a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAf0i1R9FsYl-gBtkaPiQ0PM-VeRh2yN4',
    appId: '1:542970368595:ios:93bc50ffc814c719ae2ca6',
    messagingSenderId: '542970368595',
    projectId: 'myberikan2-d4a1c',
    storageBucket: 'myberikan2-d4a1c.firebasestorage.app',
    iosClientId: '542970368595-m0rf1gvg4hq7vvec545dom0k639n2kp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myberikan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAf0i1R9FsYl-gBtkaPiQ0PM-VeRh2yN4',
    appId: '1:542970368595:ios:93bc50ffc814c719ae2ca6',
    messagingSenderId: '542970368595',
    projectId: 'myberikan2-d4a1c',
    storageBucket: 'myberikan2-d4a1c.firebasestorage.app',
    iosClientId: '542970368595-m0rf1gvg4hq7vvec545dom0k639n2kp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myberikan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChIC6EfvwdRxTxBcCou3g3do7_Tlxq6N4',
    appId: '1:542970368595:web:fe3821c5b07d804aae2ca6',
    messagingSenderId: '542970368595',
    projectId: 'myberikan2-d4a1c',
    authDomain: 'myberikan2-d4a1c.firebaseapp.com',
    storageBucket: 'myberikan2-d4a1c.firebasestorage.app',
  );

}